version: '3.8'
services:

  database-ecommerce:
    image: mysql:latest
    container_name: database-ecommerce
    ports:
      - '33061:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db-dev 
      MYSQL_USER: user 
      MYSQL_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - nestjs-network
    command: --default-authentication-plugin=mysql_native_password
volumes:
  db-data:

networks:
  nestjs-network:
    driver: bridge